# Generated by Django 6.0.7 on 2026-07-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Real photo URL for this category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External photo URL (used if no image uploaded)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🛒', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='emoji',
            field=models.CharField(default='🛒', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
